name: Render Drawio

on:
  push:
    branches:
      - master
    paths:
      - "**.drawio"
      - .github/workflows/render-drawio.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - uses: rlespinasse/drawio-export-action@v2
      with:
        format: png
        path: ./hbr.drawio
        output: ./hbr-relationship.png
    
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        file_pattern: ./*.png
        commit_message: "Update hbr-relationship.png"
        commit_options: '--no-verify --signoff'
        commit_user_name: ${{ github.actor }}
        commit_user_email: ${{ github.actor }}@users.noreply.github.com
        commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>